// This file is auto-generated by @hey-api/openapi-ts

export type ErrorResponseDto = {
    errorCode?: string;
    errorMessage?: string;
    systemMessage?: string;
};

export type UserInfoDto = {
    coId?: string;
    creUsrId?: string;
    updUsrId?: string;
    creDt?: string;
    updDt?: string;
    useFlg?: string;
    procFlag?: string;
    usrId?: string;
    usrPwd?: string;
    usrNm?: string;
    usrEml?: string;
    roleId?: string;
    roleNm?: string;
    langVal?: string;
    sysModVal?: string;
    dtFmtVal?: string;
    sysColrVal?: string;
    usrPhn?: string;
    usrAddr?: string;
    usrDesc?: string;
};

export type SuccessDto = {
    success?: boolean;
};

export type DynamicFilterDto = {
    field?: string;
    operator?: string;
    value?: unknown;
    valueTo?: unknown;
    valueType?: string;
};

export type PaginationDto = {
    pageSize?: number;
    current?: number;
};

export type SearchUserDto = {
    coId?: string;
    usrId?: string;
    usrNm?: string;
    useFlg?: string;
    filters?: Array<DynamicFilterDto>;
    sort?: SortDto;
    pagination?: PaginationDto;
};

export type SortDto = {
    sortField?: string;
    sortType?: string;
};

export type UserInfoListDto = {
    userInfo?: Array<UserInfoDto>;
    total?: number;
};

export type RoleAuthDto = {
    coId?: string;
    creUsrId?: string;
    updUsrId?: string;
    creDt?: string;
    updDt?: string;
    useFlg?: string;
    procFlag?: string;
    roleId?: string;
    pgmId?: string;
    permId?: string;
    pgmCd?: string;
    pgmTpCd?: string;
    permCd?: string;
    activeYn?: string;
};

export type RoleDto = {
    coId?: string;
    creUsrId?: string;
    updUsrId?: string;
    creDt?: string;
    updDt?: string;
    useFlg?: string;
    procFlag?: string;
    roleId?: string;
    roleCd?: string;
    roleNm?: string;
    roleDesc?: string;
    roleAuthList?: Array<RoleAuthDto>;
};

export type SearchRoleDto = {
    coId?: string;
    roleId?: string;
    roleCd?: string;
    roleNm?: string;
    pgmId?: string;
    permId?: string;
    useFlg?: string;
    sort?: SortDto;
    pagination?: PaginationDto;
};

export type RoleListDto = {
    roleList?: Array<RoleDto>;
    total?: number;
};

export type PermissionDto = {
    coId?: string;
    creUsrId?: string;
    updUsrId?: string;
    creDt?: string;
    updDt?: string;
    useFlg?: string;
    procFlag?: string;
    pgmId?: string;
    permId?: string;
    permCd?: string;
    permNm?: string;
};

export type ProgramDto = {
    coId?: string;
    creUsrId?: string;
    updUsrId?: string;
    creDt?: string;
    updDt?: string;
    useFlg?: string;
    procFlag?: string;
    pgmId?: string;
    pgmCd?: string;
    pgmNm?: string;
    pgmTpCd?: string;
    prntPgmId?: string;
    pgmRmk?: string;
    dspOrder?: number;
    level?: number;
    treeKey?: string;
    treePath?: string;
    permList?: Array<PermissionDto>;
};

export type SearchProgramDto = {
    coId?: string;
    pgmId?: string;
    pgmCd?: string;
    pgmNm?: string;
    pgmTpCd?: string;
    useFlg?: string;
    sort?: SortDto;
    pagination?: PaginationDto;
};

export type ProgramListDto = {
    programList?: Array<ProgramDto>;
    total?: number;
};

export type MasterCodeDto = {
    coId?: string;
    creUsrId?: string;
    updUsrId?: string;
    creDt?: string;
    updDt?: string;
    useFlg?: string;
    procFlag?: string;
    mstCd?: string;
    mstNm?: string;
    mstDesc?: string;
    subCdList?: Array<SubCodeDto>;
};

export type SubCodeDto = {
    coId?: string;
    creUsrId?: string;
    updUsrId?: string;
    creDt?: string;
    updDt?: string;
    useFlg?: string;
    procFlag?: string;
    mstCd?: string;
    subCd?: string;
    subNm?: string;
    subDesc?: string;
    subOrdNo?: number;
};

export type SearchMasterCodeDto = {
    coId?: string;
    mstCd?: string;
    mstNm?: string;
    useFlg?: string;
    sort?: SortDto;
    pagination?: PaginationDto;
};

export type MasterCodeListDto = {
    masterCodeList?: Array<MasterCodeDto>;
    total?: number;
};

export type FileDto = {
    coId?: string;
    creUsrId?: string;
    updUsrId?: string;
    creDt?: string;
    updDt?: string;
    useFlg?: string;
    procFlag?: string;
    fileId?: string;
    fileNm?: string;
    filePath?: string;
    fileTp?: string;
    fileSz?: number;
    file?: Blob | File;
};

export type SearchExportJobDto = {
    coId?: string;
    creUsrId?: string;
    updUsrId?: string;
    creDt?: string;
    updDt?: string;
    useFlg?: string;
    procFlag?: string;
    jbId?: string;
    jbIds?: Array<string>;
    sort?: SortDto;
    pagination?: PaginationDto;
};

export type ExportJobDto = {
    coId?: string;
    creUsrId?: string;
    updUsrId?: string;
    creDt?: string;
    updDt?: string;
    useFlg?: string;
    procFlag?: string;
    jbId?: string;
    jbSts?: string;
    jbProg?: number;
    jbRqstPara?: JsonNode;
    errMsg?: string;
    fileNm?: string;
    fileId?: string;
    totalRows?: number;
};

export type ExportJobListDto = {
    jobs?: Array<ExportJobDto>;
    total?: number;
};

export type JsonNode = unknown;

export type SearchErrorLogDto = {
    coId?: string;
    creUsrId?: string;
    updUsrId?: string;
    creDt?: string;
    updDt?: string;
    useFlg?: string;
    procFlag?: string;
    dateFm?: string;
    dateTo?: string;
    endPoint?: string;
    sort?: SortDto;
    pagination?: PaginationDto;
};

export type ErrorLogDto = {
    coId?: string;
    creUsrId?: string;
    updUsrId?: string;
    creDt?: string;
    updDt?: string;
    useFlg?: string;
    procFlag?: string;
    msgId?: string;
    errMsg?: string;
    endpoint?: string;
    rqstPara?: JsonNode;
    mdlNm?: string;
    stackTrace?: string;
};

export type ErrorLogListDto = {
    messageList?: Array<ErrorLogDto>;
    total?: number;
};

export type ComMsgDto = {
    coId?: string;
    creUsrId?: string;
    updUsrId?: string;
    creDt?: string;
    updDt?: string;
    useFlg?: string;
    procFlag?: string;
    msgId?: string;
    dfltMsgVal?: string;
    mdlNm?: string;
    msgTpVal?: string;
    translations?: Array<ComMsgTransDto>;
};

export type ComMsgTransDto = {
    coId?: string;
    creUsrId?: string;
    updUsrId?: string;
    creDt?: string;
    updDt?: string;
    useFlg?: string;
    procFlag?: string;
    msgId?: string;
    langVal?: string;
    transMsgVal?: string;
};

export type SearchComMsgDto = {
    coId?: string;
    creUsrId?: string;
    updUsrId?: string;
    creDt?: string;
    updDt?: string;
    useFlg?: string;
    procFlag?: string;
    msgId?: string;
    dfltMsgVal?: string;
    mdlNm?: string;
    msgTpVal?: string;
    langVal?: string;
    sort?: SortDto;
    pagination?: PaginationDto;
};

export type ComMsgListDto = {
    messageList?: Array<ComMsgDto>;
    total?: number;
};

export type BatchJobConfigDto = {
    coId?: string;
    creUsrId?: string;
    updUsrId?: string;
    creDt?: string;
    updDt?: string;
    useFlg?: string;
    procFlag?: string;
    batJbId?: string;
    batJbNm?: string;
    batJbClss?: string;
    batJbStsCd?: string;
    batJbDesc?: string;
    cronXprVal?: string;
    cronDesc?: string;
    batJbLstRunDt?: string;
    batJbNxtRunDt?: string;
};

export type SearchBatchJobConfigDto = {
    coId?: string;
    creUsrId?: string;
    updUsrId?: string;
    creDt?: string;
    updDt?: string;
    useFlg?: string;
    procFlag?: string;
    batJbId?: string;
    batJbNm?: string;
    sort?: SortDto;
};

export type SearchBatchJobExecutionHistoryDto = {
    coId?: string;
    creUsrId?: string;
    updUsrId?: string;
    creDt?: string;
    updDt?: string;
    useFlg?: string;
    procFlag?: string;
    batJbId?: string;
    sort?: SortDto;
    pagination?: PaginationDto;
};

export type BatchJobExecutionHistoryDto = {
    coId?: string;
    creUsrId?: string;
    updUsrId?: string;
    creDt?: string;
    updDt?: string;
    useFlg?: string;
    procFlag?: string;
    batExecId?: string;
    batJbId?: string;
    batJbStsCd?: string;
    batJbStDt?: string;
    batJbEndDt?: string;
    batJbPara?: JsonNode;
    batJbMsg?: string;
    batJbNxtRunDt?: string;
};

export type BatchJobExecutionHistoryListDto = {
    executionHistory?: Array<BatchJobExecutionHistoryDto>;
    total?: number;
};

export type RefreshTokenRequestDto = {
    refreshToken?: string;
};

export type RefreshTokenResponseDto = {
    accessToken?: string;
    accessExpireIn?: number;
    refreshToken?: string;
    refreshExpireIn?: number;
};

export type LoginRequestDto = {
    username?: string;
    password?: string;
};

export type LoginResponseDto = {
    accessToken?: string;
    accessExpireIn?: number;
    refreshToken?: string;
    refreshExpireIn?: number;
};

export type FavoriteDto = {
    coId?: string;
    creUsrId?: string;
    updUsrId?: string;
    creDt?: string;
    updDt?: string;
    useFlg?: string;
    procFlag?: string;
    favId?: number;
    usrId?: string;
    pgmCd?: string;
};

export type UpdateUserData = {
    body: UserInfoDto;
    path?: never;
    query?: never;
    url: '/api/user/updateUser';
};

export type UpdateUserErrors = {
    /**
     * Forbidden
     */
    403: ErrorResponseDto;
    /**
     * Internal Server Error
     */
    500: ErrorResponseDto;
};

export type UpdateUserError = UpdateUserErrors[keyof UpdateUserErrors];

export type UpdateUserResponses = {
    /**
     * OK
     */
    200: SuccessDto;
};

export type UpdateUserResponse = UpdateUserResponses[keyof UpdateUserResponses];

export type SaveUserSettingData = {
    body: UserInfoDto;
    path?: never;
    query?: never;
    url: '/api/user/saveUserSetting';
};

export type SaveUserSettingErrors = {
    /**
     * Forbidden
     */
    403: ErrorResponseDto;
    /**
     * Internal Server Error
     */
    500: ErrorResponseDto;
};

export type SaveUserSettingError = SaveUserSettingErrors[keyof SaveUserSettingErrors];

export type SaveUserSettingResponses = {
    /**
     * OK
     */
    200: SuccessDto;
};

export type SaveUserSettingResponse = SaveUserSettingResponses[keyof SaveUserSettingResponses];

export type ResetUserPasswordData = {
    body: Array<UserInfoDto>;
    path?: never;
    query?: never;
    url: '/api/user/resetUserPassword';
};

export type ResetUserPasswordErrors = {
    /**
     * Forbidden
     */
    403: ErrorResponseDto;
    /**
     * Internal Server Error
     */
    500: ErrorResponseDto;
};

export type ResetUserPasswordError = ResetUserPasswordErrors[keyof ResetUserPasswordErrors];

export type ResetUserPasswordResponses = {
    /**
     * OK
     */
    200: SuccessDto;
};

export type ResetUserPasswordResponse = ResetUserPasswordResponses[keyof ResetUserPasswordResponses];

export type GetUserInfoData = {
    body: SearchUserDto;
    path?: never;
    query?: never;
    url: '/api/user/getUserInfo';
};

export type GetUserInfoErrors = {
    /**
     * Forbidden
     */
    403: ErrorResponseDto;
    /**
     * Internal Server Error
     */
    500: ErrorResponseDto;
};

export type GetUserInfoError = GetUserInfoErrors[keyof GetUserInfoErrors];

export type GetUserInfoResponses = {
    /**
     * OK
     */
    200: UserInfoDto;
};

export type GetUserInfoResponse = GetUserInfoResponses[keyof GetUserInfoResponses];

export type GetListUserInfoData = {
    body: SearchUserDto;
    path?: never;
    query?: never;
    url: '/api/user/getListUserInfo';
};

export type GetListUserInfoErrors = {
    /**
     * Forbidden
     */
    403: ErrorResponseDto;
    /**
     * Internal Server Error
     */
    500: ErrorResponseDto;
};

export type GetListUserInfoError = GetListUserInfoErrors[keyof GetListUserInfoErrors];

export type GetListUserInfoResponses = {
    /**
     * OK
     */
    200: UserInfoListDto;
};

export type GetListUserInfoResponse = GetListUserInfoResponses[keyof GetListUserInfoResponses];

export type ExportExcelData = {
    body: SearchUserDto;
    path?: never;
    query?: never;
    url: '/api/user/exportExcel';
};

export type ExportExcelErrors = {
    /**
     * Forbidden
     */
    403: ErrorResponseDto;
    /**
     * Internal Server Error
     */
    500: ErrorResponseDto;
};

export type ExportExcelError = ExportExcelErrors[keyof ExportExcelErrors];

export type ExportExcelResponses = {
    /**
     * OK
     */
    200: {
        [key: string]: unknown;
    };
};

export type ExportExcelResponse = ExportExcelResponses[keyof ExportExcelResponses];

export type CreateUserData = {
    body: UserInfoDto;
    path?: never;
    query?: never;
    url: '/api/user/createUser';
};

export type CreateUserErrors = {
    /**
     * Forbidden
     */
    403: ErrorResponseDto;
    /**
     * Internal Server Error
     */
    500: ErrorResponseDto;
};

export type CreateUserError = CreateUserErrors[keyof CreateUserErrors];

export type CreateUserResponses = {
    /**
     * OK
     */
    200: SuccessDto;
};

export type CreateUserResponse = CreateUserResponses[keyof CreateUserResponses];

export type UpdateRoleData = {
    body: RoleDto;
    path?: never;
    query?: never;
    url: '/api/role/updateRole';
};

export type UpdateRoleErrors = {
    /**
     * Forbidden
     */
    403: ErrorResponseDto;
    /**
     * Internal Server Error
     */
    500: ErrorResponseDto;
};

export type UpdateRoleError = UpdateRoleErrors[keyof UpdateRoleErrors];

export type UpdateRoleResponses = {
    /**
     * OK
     */
    200: SuccessDto;
};

export type UpdateRoleResponse = UpdateRoleResponses[keyof UpdateRoleResponses];

export type InsertRoleData = {
    body: RoleDto;
    path?: never;
    query?: never;
    url: '/api/role/insertRole';
};

export type InsertRoleErrors = {
    /**
     * Forbidden
     */
    403: ErrorResponseDto;
    /**
     * Internal Server Error
     */
    500: ErrorResponseDto;
};

export type InsertRoleError = InsertRoleErrors[keyof InsertRoleErrors];

export type InsertRoleResponses = {
    /**
     * OK
     */
    200: SuccessDto;
};

export type InsertRoleResponse = InsertRoleResponses[keyof InsertRoleResponses];

export type GetRoleData = {
    body: SearchRoleDto;
    path?: never;
    query?: never;
    url: '/api/role/getRole';
};

export type GetRoleErrors = {
    /**
     * Forbidden
     */
    403: ErrorResponseDto;
    /**
     * Internal Server Error
     */
    500: ErrorResponseDto;
};

export type GetRoleError = GetRoleErrors[keyof GetRoleErrors];

export type GetRoleResponses = {
    /**
     * OK
     */
    200: RoleDto;
};

export type GetRoleResponse = GetRoleResponses[keyof GetRoleResponses];

export type GetRoleListData = {
    body: SearchRoleDto;
    path?: never;
    query?: never;
    url: '/api/role/getRoleList';
};

export type GetRoleListErrors = {
    /**
     * Forbidden
     */
    403: ErrorResponseDto;
    /**
     * Internal Server Error
     */
    500: ErrorResponseDto;
};

export type GetRoleListError = GetRoleListErrors[keyof GetRoleListErrors];

export type GetRoleListResponses = {
    /**
     * OK
     */
    200: RoleListDto;
};

export type GetRoleListResponse = GetRoleListResponses[keyof GetRoleListResponses];

export type UpdateProgramData = {
    body: ProgramDto;
    path?: never;
    query?: never;
    url: '/api/program/updateProgram';
};

export type UpdateProgramErrors = {
    /**
     * Forbidden
     */
    403: ErrorResponseDto;
    /**
     * Internal Server Error
     */
    500: ErrorResponseDto;
};

export type UpdateProgramError = UpdateProgramErrors[keyof UpdateProgramErrors];

export type UpdateProgramResponses = {
    /**
     * OK
     */
    200: SuccessDto;
};

export type UpdateProgramResponse = UpdateProgramResponses[keyof UpdateProgramResponses];

export type SavePermissionByProgramData = {
    body: Array<PermissionDto>;
    path?: never;
    query?: never;
    url: '/api/program/savePermissionsByProgram';
};

export type SavePermissionByProgramErrors = {
    /**
     * Forbidden
     */
    403: ErrorResponseDto;
    /**
     * Internal Server Error
     */
    500: ErrorResponseDto;
};

export type SavePermissionByProgramError = SavePermissionByProgramErrors[keyof SavePermissionByProgramErrors];

export type SavePermissionByProgramResponses = {
    /**
     * OK
     */
    200: SuccessDto;
};

export type SavePermissionByProgramResponse = SavePermissionByProgramResponses[keyof SavePermissionByProgramResponses];

export type InsertProgramData = {
    body: ProgramDto;
    path?: never;
    query?: never;
    url: '/api/program/insertProgram';
};

export type InsertProgramErrors = {
    /**
     * Forbidden
     */
    403: ErrorResponseDto;
    /**
     * Internal Server Error
     */
    500: ErrorResponseDto;
};

export type InsertProgramError = InsertProgramErrors[keyof InsertProgramErrors];

export type InsertProgramResponses = {
    /**
     * OK
     */
    200: SuccessDto;
};

export type InsertProgramResponse = InsertProgramResponses[keyof InsertProgramResponses];

export type GetProgramData = {
    body: SearchProgramDto;
    path?: never;
    query?: never;
    url: '/api/program/getProgram';
};

export type GetProgramErrors = {
    /**
     * Forbidden
     */
    403: ErrorResponseDto;
    /**
     * Internal Server Error
     */
    500: ErrorResponseDto;
};

export type GetProgramError = GetProgramErrors[keyof GetProgramErrors];

export type GetProgramResponses = {
    /**
     * OK
     */
    200: ProgramDto;
};

export type GetProgramResponse = GetProgramResponses[keyof GetProgramResponses];

export type GetProgramListData = {
    body: SearchProgramDto;
    path?: never;
    query?: never;
    url: '/api/program/getProgramList';
};

export type GetProgramListErrors = {
    /**
     * Forbidden
     */
    403: ErrorResponseDto;
    /**
     * Internal Server Error
     */
    500: ErrorResponseDto;
};

export type GetProgramListError = GetProgramListErrors[keyof GetProgramListErrors];

export type GetProgramListResponses = {
    /**
     * OK
     */
    200: ProgramListDto;
};

export type GetProgramListResponse = GetProgramListResponses[keyof GetProgramListResponses];

export type GetPermissionByProgramData = {
    body: ProgramDto;
    path?: never;
    query?: never;
    url: '/api/program/getPermissionByProgram';
};

export type GetPermissionByProgramErrors = {
    /**
     * Forbidden
     */
    403: ErrorResponseDto;
    /**
     * Internal Server Error
     */
    500: ErrorResponseDto;
};

export type GetPermissionByProgramError = GetPermissionByProgramErrors[keyof GetPermissionByProgramErrors];

export type GetPermissionByProgramResponses = {
    /**
     * OK
     */
    200: Array<PermissionDto>;
};

export type GetPermissionByProgramResponse = GetPermissionByProgramResponses[keyof GetPermissionByProgramResponses];

export type DeleteProgramData = {
    body: Array<ProgramDto>;
    path?: never;
    query?: never;
    url: '/api/program/deletePrograms';
};

export type DeleteProgramErrors = {
    /**
     * Forbidden
     */
    403: ErrorResponseDto;
    /**
     * Internal Server Error
     */
    500: ErrorResponseDto;
};

export type DeleteProgramError = DeleteProgramErrors[keyof DeleteProgramErrors];

export type DeleteProgramResponses = {
    /**
     * OK
     */
    200: SuccessDto;
};

export type DeleteProgramResponse = DeleteProgramResponses[keyof DeleteProgramResponses];

export type UpdateMasterCodeData = {
    body: MasterCodeDto;
    path?: never;
    query?: never;
    url: '/api/masterCode/updateMasterCode';
};

export type UpdateMasterCodeErrors = {
    /**
     * Forbidden
     */
    403: ErrorResponseDto;
    /**
     * Internal Server Error
     */
    500: ErrorResponseDto;
};

export type UpdateMasterCodeError = UpdateMasterCodeErrors[keyof UpdateMasterCodeErrors];

export type UpdateMasterCodeResponses = {
    /**
     * OK
     */
    200: SuccessDto;
};

export type UpdateMasterCodeResponse = UpdateMasterCodeResponses[keyof UpdateMasterCodeResponses];

export type InsertMasterCodeData = {
    body: MasterCodeDto;
    path?: never;
    query?: never;
    url: '/api/masterCode/insertMasterCode';
};

export type InsertMasterCodeErrors = {
    /**
     * Forbidden
     */
    403: ErrorResponseDto;
    /**
     * Internal Server Error
     */
    500: ErrorResponseDto;
};

export type InsertMasterCodeError = InsertMasterCodeErrors[keyof InsertMasterCodeErrors];

export type InsertMasterCodeResponses = {
    /**
     * OK
     */
    200: SuccessDto;
};

export type InsertMasterCodeResponse = InsertMasterCodeResponses[keyof InsertMasterCodeResponses];

export type GetMasterCodeData = {
    body: SearchMasterCodeDto;
    path?: never;
    query?: never;
    url: '/api/masterCode/getMasterCode';
};

export type GetMasterCodeErrors = {
    /**
     * Forbidden
     */
    403: ErrorResponseDto;
    /**
     * Internal Server Error
     */
    500: ErrorResponseDto;
};

export type GetMasterCodeError = GetMasterCodeErrors[keyof GetMasterCodeErrors];

export type GetMasterCodeResponses = {
    /**
     * OK
     */
    200: MasterCodeDto;
};

export type GetMasterCodeResponse = GetMasterCodeResponses[keyof GetMasterCodeResponses];

export type GetMasterCodeListData = {
    body: SearchMasterCodeDto;
    path?: never;
    query?: never;
    url: '/api/masterCode/getMasterCodeList';
};

export type GetMasterCodeListErrors = {
    /**
     * Forbidden
     */
    403: ErrorResponseDto;
    /**
     * Internal Server Error
     */
    500: ErrorResponseDto;
};

export type GetMasterCodeListError = GetMasterCodeListErrors[keyof GetMasterCodeListErrors];

export type GetMasterCodeListResponses = {
    /**
     * OK
     */
    200: MasterCodeListDto;
};

export type GetMasterCodeListResponse = GetMasterCodeListResponses[keyof GetMasterCodeListResponses];

export type UploadData = {
    body?: never;
    path?: never;
    query: {
        file: FileDto;
    };
    url: '/api/file/upload';
};

export type UploadErrors = {
    /**
     * Forbidden
     */
    403: ErrorResponseDto;
    /**
     * Internal Server Error
     */
    500: ErrorResponseDto;
};

export type UploadError = UploadErrors[keyof UploadErrors];

export type UploadResponses = {
    /**
     * OK
     */
    200: SuccessDto;
};

export type UploadResponse = UploadResponses[keyof UploadResponses];

export type GetExportJobListData = {
    body: SearchExportJobDto;
    path?: never;
    query?: never;
    url: '/api/exportJob/getExportJobList';
};

export type GetExportJobListErrors = {
    /**
     * Forbidden
     */
    403: ErrorResponseDto;
    /**
     * Internal Server Error
     */
    500: ErrorResponseDto;
};

export type GetExportJobListError = GetExportJobListErrors[keyof GetExportJobListErrors];

export type GetExportJobListResponses = {
    /**
     * OK
     */
    200: ExportJobListDto;
};

export type GetExportJobListResponse = GetExportJobListResponses[keyof GetExportJobListResponses];

export type GetHistoryListData = {
    body: SearchErrorLogDto;
    path?: never;
    query?: never;
    url: '/api/errorLog/getHistoryList';
};

export type GetHistoryListErrors = {
    /**
     * Forbidden
     */
    403: ErrorResponseDto;
    /**
     * Internal Server Error
     */
    500: ErrorResponseDto;
};

export type GetHistoryListError = GetHistoryListErrors[keyof GetHistoryListErrors];

export type GetHistoryListResponses = {
    /**
     * OK
     */
    200: ErrorLogListDto;
};

export type GetHistoryListResponse = GetHistoryListResponses[keyof GetHistoryListResponses];

export type UpdateMessageData = {
    body: ComMsgDto;
    path?: never;
    query?: never;
    url: '/api/comMsg/updateMessage';
};

export type UpdateMessageErrors = {
    /**
     * Forbidden
     */
    403: ErrorResponseDto;
    /**
     * Internal Server Error
     */
    500: ErrorResponseDto;
};

export type UpdateMessageError = UpdateMessageErrors[keyof UpdateMessageErrors];

export type UpdateMessageResponses = {
    /**
     * OK
     */
    200: SuccessDto;
};

export type UpdateMessageResponse = UpdateMessageResponses[keyof UpdateMessageResponses];

export type InsertMessageData = {
    body: ComMsgDto;
    path?: never;
    query?: never;
    url: '/api/comMsg/insertMessage';
};

export type InsertMessageErrors = {
    /**
     * Forbidden
     */
    403: ErrorResponseDto;
    /**
     * Internal Server Error
     */
    500: ErrorResponseDto;
};

export type InsertMessageError = InsertMessageErrors[keyof InsertMessageErrors];

export type InsertMessageResponses = {
    /**
     * OK
     */
    200: SuccessDto;
};

export type InsertMessageResponse = InsertMessageResponses[keyof InsertMessageResponses];

export type GetMessageData = {
    body: SearchComMsgDto;
    path?: never;
    query?: never;
    url: '/api/comMsg/getMessage';
};

export type GetMessageErrors = {
    /**
     * Forbidden
     */
    403: ErrorResponseDto;
    /**
     * Internal Server Error
     */
    500: ErrorResponseDto;
};

export type GetMessageError = GetMessageErrors[keyof GetMessageErrors];

export type GetMessageResponses = {
    /**
     * OK
     */
    200: ComMsgDto;
};

export type GetMessageResponse = GetMessageResponses[keyof GetMessageResponses];

export type GetMessageListData = {
    body: SearchComMsgDto;
    path?: never;
    query?: never;
    url: '/api/comMsg/getMessageList';
};

export type GetMessageListErrors = {
    /**
     * Forbidden
     */
    403: ErrorResponseDto;
    /**
     * Internal Server Error
     */
    500: ErrorResponseDto;
};

export type GetMessageListError = GetMessageListErrors[keyof GetMessageListErrors];

export type GetMessageListResponses = {
    /**
     * OK
     */
    200: ComMsgListDto;
};

export type GetMessageListResponse = GetMessageListResponses[keyof GetMessageListResponses];

export type DeleteMessageData = {
    body: Array<ComMsgDto>;
    path?: never;
    query?: never;
    url: '/api/comMsg/deleteMessage';
};

export type DeleteMessageErrors = {
    /**
     * Forbidden
     */
    403: ErrorResponseDto;
    /**
     * Internal Server Error
     */
    500: ErrorResponseDto;
};

export type DeleteMessageError = DeleteMessageErrors[keyof DeleteMessageErrors];

export type DeleteMessageResponses = {
    /**
     * OK
     */
    200: SuccessDto;
};

export type DeleteMessageResponse = DeleteMessageResponses[keyof DeleteMessageResponses];

export type UpdateData = {
    body: BatchJobConfigDto;
    path?: never;
    query?: never;
    url: '/api/batch/update';
};

export type UpdateErrors = {
    /**
     * Forbidden
     */
    403: ErrorResponseDto;
    /**
     * Internal Server Error
     */
    500: ErrorResponseDto;
};

export type UpdateError = UpdateErrors[keyof UpdateErrors];

export type UpdateResponses = {
    /**
     * OK
     */
    200: SuccessDto;
};

export type UpdateResponse = UpdateResponses[keyof UpdateResponses];

export type ResumeJobData = {
    body: BatchJobConfigDto;
    path?: never;
    query?: never;
    url: '/api/batch/resume';
};

export type ResumeJobErrors = {
    /**
     * Forbidden
     */
    403: ErrorResponseDto;
    /**
     * Internal Server Error
     */
    500: ErrorResponseDto;
};

export type ResumeJobError = ResumeJobErrors[keyof ResumeJobErrors];

export type ResumeJobResponses = {
    /**
     * OK
     */
    200: SuccessDto;
};

export type ResumeJobResponse = ResumeJobResponses[keyof ResumeJobResponses];

export type RegisterData = {
    body: BatchJobConfigDto;
    path?: never;
    query?: never;
    url: '/api/batch/register';
};

export type RegisterErrors = {
    /**
     * Forbidden
     */
    403: ErrorResponseDto;
    /**
     * Internal Server Error
     */
    500: ErrorResponseDto;
};

export type RegisterError = RegisterErrors[keyof RegisterErrors];

export type RegisterResponses = {
    /**
     * OK
     */
    200: SuccessDto;
};

export type RegisterResponse = RegisterResponses[keyof RegisterResponses];

export type PauseJobData = {
    body: BatchJobConfigDto;
    path?: never;
    query?: never;
    url: '/api/batch/pause';
};

export type PauseJobErrors = {
    /**
     * Forbidden
     */
    403: ErrorResponseDto;
    /**
     * Internal Server Error
     */
    500: ErrorResponseDto;
};

export type PauseJobError = PauseJobErrors[keyof PauseJobErrors];

export type PauseJobResponses = {
    /**
     * OK
     */
    200: SuccessDto;
};

export type PauseJobResponse = PauseJobResponses[keyof PauseJobResponses];

export type GetBatchJobData = {
    body: SearchBatchJobConfigDto;
    path?: never;
    query?: never;
    url: '/api/batch/getBatchJob';
};

export type GetBatchJobErrors = {
    /**
     * Forbidden
     */
    403: ErrorResponseDto;
    /**
     * Internal Server Error
     */
    500: ErrorResponseDto;
};

export type GetBatchJobError = GetBatchJobErrors[keyof GetBatchJobErrors];

export type GetBatchJobResponses = {
    /**
     * OK
     */
    200: BatchJobConfigDto;
};

export type GetBatchJobResponse = GetBatchJobResponses[keyof GetBatchJobResponses];

export type GetBatchJobListData = {
    body: SearchBatchJobConfigDto;
    path?: never;
    query?: never;
    url: '/api/batch/getBatchJobList';
};

export type GetBatchJobListErrors = {
    /**
     * Forbidden
     */
    403: ErrorResponseDto;
    /**
     * Internal Server Error
     */
    500: ErrorResponseDto;
};

export type GetBatchJobListError = GetBatchJobListErrors[keyof GetBatchJobListErrors];

export type GetBatchJobListResponses = {
    /**
     * OK
     */
    200: Array<BatchJobConfigDto>;
};

export type GetBatchJobListResponse = GetBatchJobListResponses[keyof GetBatchJobListResponses];

export type GetBatchJobHistoryListData = {
    body: SearchBatchJobExecutionHistoryDto;
    path?: never;
    query?: never;
    url: '/api/batch/getBatchJobHistoryList';
};

export type GetBatchJobHistoryListErrors = {
    /**
     * Forbidden
     */
    403: ErrorResponseDto;
    /**
     * Internal Server Error
     */
    500: ErrorResponseDto;
};

export type GetBatchJobHistoryListError = GetBatchJobHistoryListErrors[keyof GetBatchJobHistoryListErrors];

export type GetBatchJobHistoryListResponses = {
    /**
     * OK
     */
    200: BatchJobExecutionHistoryListDto;
};

export type GetBatchJobHistoryListResponse = GetBatchJobHistoryListResponses[keyof GetBatchJobHistoryListResponses];

export type RefreshData = {
    body: RefreshTokenRequestDto;
    path?: never;
    query?: never;
    url: '/api/auth/refresh-token';
};

export type RefreshErrors = {
    /**
     * Forbidden
     */
    403: ErrorResponseDto;
    /**
     * Internal Server Error
     */
    500: ErrorResponseDto;
};

export type RefreshError = RefreshErrors[keyof RefreshErrors];

export type RefreshResponses = {
    /**
     * OK
     */
    200: RefreshTokenResponseDto;
};

export type RefreshResponse = RefreshResponses[keyof RefreshResponses];

export type LogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/logout';
};

export type LogoutErrors = {
    /**
     * Forbidden
     */
    403: ErrorResponseDto;
    /**
     * Internal Server Error
     */
    500: ErrorResponseDto;
};

export type LogoutError = LogoutErrors[keyof LogoutErrors];

export type LogoutResponses = {
    /**
     * OK
     */
    200: SuccessDto;
};

export type LogoutResponse = LogoutResponses[keyof LogoutResponses];

export type LoginData = {
    body: LoginRequestDto;
    path?: never;
    query?: never;
    url: '/api/auth/login';
};

export type LoginErrors = {
    /**
     * Forbidden
     */
    403: ErrorResponseDto;
    /**
     * Internal Server Error
     */
    500: ErrorResponseDto;
};

export type LoginError = LoginErrors[keyof LoginErrors];

export type LoginResponses = {
    /**
     * OK
     */
    200: LoginResponseDto;
};

export type LoginResponse = LoginResponses[keyof LoginResponses];

export type GetUserFavoritesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/adm/favorites';
};

export type GetUserFavoritesErrors = {
    /**
     * Forbidden
     */
    403: ErrorResponseDto;
    /**
     * Internal Server Error
     */
    500: ErrorResponseDto;
};

export type GetUserFavoritesError = GetUserFavoritesErrors[keyof GetUserFavoritesErrors];

export type GetUserFavoritesResponses = {
    /**
     * OK
     */
    200: Array<FavoriteDto>;
};

export type GetUserFavoritesResponse = GetUserFavoritesResponses[keyof GetUserFavoritesResponses];

export type AddFavoriteData = {
    body: FavoriteDto;
    path?: never;
    query?: never;
    url: '/api/adm/favorites';
};

export type AddFavoriteErrors = {
    /**
     * Forbidden
     */
    403: ErrorResponseDto;
    /**
     * Internal Server Error
     */
    500: ErrorResponseDto;
};

export type AddFavoriteError = AddFavoriteErrors[keyof AddFavoriteErrors];

export type AddFavoriteResponses = {
    /**
     * OK
     */
    200: SuccessDto;
};

export type AddFavoriteResponse = AddFavoriteResponses[keyof AddFavoriteResponses];

export type GenerateEmployeeListReportData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/reports/employee/list';
};

export type GenerateEmployeeListReportErrors = {
    /**
     * Forbidden
     */
    403: ErrorResponseDto;
    /**
     * Internal Server Error
     */
    500: ErrorResponseDto;
};

export type GenerateEmployeeListReportError = GenerateEmployeeListReportErrors[keyof GenerateEmployeeListReportErrors];

export type GenerateEmployeeListReportResponses = {
    /**
     * OK
     */
    200: string;
};

export type GenerateEmployeeListReportResponse = GenerateEmployeeListReportResponses[keyof GenerateEmployeeListReportResponses];

export type RunJobData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/job/run';
};

export type RunJobErrors = {
    /**
     * Forbidden
     */
    403: ErrorResponseDto;
    /**
     * Internal Server Error
     */
    500: ErrorResponseDto;
};

export type RunJobError = RunJobErrors[keyof RunJobErrors];

export type RunJobResponses = {
    /**
     * OK
     */
    200: {
        [key: string]: unknown;
    };
};

export type RunJobResponse = RunJobResponses[keyof RunJobResponses];

export type DownloadFileData = {
    body?: never;
    headers?: {
        Range?: string;
    };
    path: {
        fileId: string;
    };
    query?: never;
    url: '/api/file/download/{fileId}';
};

export type DownloadFileErrors = {
    /**
     * Forbidden
     */
    403: ErrorResponseDto;
    /**
     * Internal Server Error
     */
    500: ErrorResponseDto;
};

export type DownloadFileError = DownloadFileErrors[keyof DownloadFileErrors];

export type DownloadFileResponses = {
    /**
     * OK
     */
    200: Blob | File;
};

export type DownloadFileResponse = DownloadFileResponses[keyof DownloadFileResponses];

export type ConfirmExportData = {
    body?: never;
    path: {
        jobId: string;
    };
    query?: never;
    url: '/api/exportJob/confirm/{jobId}';
};

export type ConfirmExportErrors = {
    /**
     * Forbidden
     */
    403: ErrorResponseDto;
    /**
     * Internal Server Error
     */
    500: ErrorResponseDto;
};

export type ConfirmExportError = ConfirmExportErrors[keyof ConfirmExportErrors];

export type ConfirmExportResponses = {
    /**
     * OK
     */
    200: {
        [key: string]: unknown;
    };
};

export type ConfirmExportResponse = ConfirmExportResponses[keyof ConfirmExportResponses];

export type CancelExportData = {
    body?: never;
    path: {
        jobId: string;
    };
    query?: never;
    url: '/api/exportJob/cancel/{jobId}';
};

export type CancelExportErrors = {
    /**
     * Forbidden
     */
    403: ErrorResponseDto;
    /**
     * Internal Server Error
     */
    500: ErrorResponseDto;
};

export type CancelExportError = CancelExportErrors[keyof CancelExportErrors];

export type CancelExportResponses = {
    /**
     * OK
     */
    200: SuccessDto;
};

export type CancelExportResponse = CancelExportResponses[keyof CancelExportResponses];

export type GetI18nMessagesForLanguageData = {
    body?: never;
    path: {
        lng: string;
    };
    query?: never;
    url: '/api/comMsg/getI18nMessages/{lng}';
};

export type GetI18nMessagesForLanguageErrors = {
    /**
     * Forbidden
     */
    403: ErrorResponseDto;
    /**
     * Internal Server Error
     */
    500: ErrorResponseDto;
};

export type GetI18nMessagesForLanguageError = GetI18nMessagesForLanguageErrors[keyof GetI18nMessagesForLanguageErrors];

export type GetI18nMessagesForLanguageResponses = {
    /**
     * OK
     */
    200: {
        [key: string]: string;
    };
};

export type GetI18nMessagesForLanguageResponse = GetI18nMessagesForLanguageResponses[keyof GetI18nMessagesForLanguageResponses];

export type GetUserRoleData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/getUserRole';
};

export type GetUserRoleErrors = {
    /**
     * Forbidden
     */
    403: ErrorResponseDto;
    /**
     * Internal Server Error
     */
    500: ErrorResponseDto;
};

export type GetUserRoleError = GetUserRoleErrors[keyof GetUserRoleErrors];

export type GetUserRoleResponses = {
    /**
     * OK
     */
    200: RoleDto;
};

export type GetUserRoleResponse = GetUserRoleResponses[keyof GetUserRoleResponses];

export type RemoveFavoriteData = {
    body?: never;
    path: {
        pgmCd: string;
    };
    query?: never;
    url: '/api/adm/favorites/{pgmCd}';
};

export type RemoveFavoriteErrors = {
    /**
     * Forbidden
     */
    403: ErrorResponseDto;
    /**
     * Internal Server Error
     */
    500: ErrorResponseDto;
};

export type RemoveFavoriteError = RemoveFavoriteErrors[keyof RemoveFavoriteErrors];

export type RemoveFavoriteResponses = {
    /**
     * OK
     */
    200: SuccessDto;
};

export type RemoveFavoriteResponse = RemoveFavoriteResponses[keyof RemoveFavoriteResponses];

export type ClientOptions = {
    baseUrl: 'http://localhost:8080' | (string & {});
};