export const QUERY_KEY = {
	COMMON: {
		GET_MESSAGE_HISTORY_LIST: 'GET_MESSAGE_HISTORY_LIST',
		GET_EXPORT_HISTORY_LIST: 'GET_EXPORT_HISTORY_LIST',
		GET_BATCH_JOB_LIST: 'GET_BATCH_JOB_LIST',
		GET_BATCH_JOB: 'GET_BATCH_JOB',
		GET_BATCH_JOB_HISTORY_LIST: 'GET_BATCH_JOB_HISTORY_LIST',
	},
	ADMIN: {
		USER_MANAGEMENT: {
			GET_USER_INFO_LIST: 'GET_USER_INFO_LIST',
			GET_USER_INFO: 'GET_USER_INFO',
		},
		ROLE_MANAGEMENT: {
			GET_ROLE_LIST: 'GET_ROLE_LIST',
			GET_ROLE: 'GET_ROLE',
			GET_PROGRAM_LIST: 'GET_PROGRAM_LIST',
			GET_PROGRAM: 'GET_PROGRAM',
			GET_PERMISSION_BY_PROGRAM: 'GET_PERMISSION_BY_PROGRAM',
		},
	},
	MASTER_DATA: {
		MASTER_CODE_MANAGEMENT: {
			GET_MASTER_CODE_LIST: 'GET_MASTER_CODE_LIST',
			GET_MASTER_CODE: 'GET_MASTER_CODE',
		},
	},
	SYSTEM_CONFIGURATION: {
		MESSAGE_MANAGEMENT: {
			GET_MESSAGE_LIST: 'GET_MESSAGE_LIST',
			GET_MESSAGE: 'GET_MESSAGE',
		},
	},
};
